version: '3.0'
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    links:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
  # couchserver:
  #   image: couchdb
  #   restart: always
  #   ports:
  #     - "5984:5984"
  #   environment:
  #     - COUCHDB_USER=admin
  #     - COUCHDB_PASSWORD=password
  #   volumes:
  #     - ./dbdata:/opt/couchdb/data